//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_NguoiDung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ADM_NguoiDung()
        {
            this.DAT_ChoLocPhienGuiDuLieu = new HashSet<DAT_ChoLocPhienGuiDuLieu>();
            this.DAT_ChuyenDoiDiaGioi = new HashSet<DAT_ChuyenDoiDiaGioi>();
            this.DAT_NhapLieuGSPH = new HashSet<DAT_NhapLieuGSPH>();
            this.DAT_NhapLieuGSPH1 = new HashSet<DAT_NhapLieuGSPH>();
            this.DAT_NhapLieuGSPH2 = new HashSet<DAT_NhapLieuGSPH>();
            this.DAT_NhapLieuGSTD = new HashSet<DAT_NhapLieuGSTD>();
            this.DAT_NhapLieuGSTD1 = new HashSet<DAT_NhapLieuGSTD>();
            this.DAT_NhapLieuGSTD2 = new HashSet<DAT_NhapLieuGSTD>();
            this.DAT_NhapLieuXetNghiem = new HashSet<DAT_NhapLieuXetNghiem>();
            this.DAT_NhapLieuXetNghiem1 = new HashSet<DAT_NhapLieuXetNghiem>();
            this.DAT_NhapLieuXetNghiem2 = new HashSet<DAT_NhapLieuXetNghiem>();
            this.DAT_PhienGuiDuLieu = new HashSet<DAT_PhienGuiDuLieu>();
            this.DAT_PhienNhanDuLieu = new HashSet<DAT_PhienNhanDuLieu>();
            this.DIC_NhapLieuTuDien = new HashSet<DIC_NhapLieuTuDien>();
            this.DIC_NhapLieuTuDien1 = new HashSet<DIC_NhapLieuTuDien>();
            this.DIC_NhapLieuTuDien2 = new HashSet<DIC_NhapLieuTuDien>();
        }
    
        public short IDNguoiDung { get; set; }
        public string TenDangNhap { get; set; }
        public string TenDayDu { get; set; }
        public string MatKhau { get; set; }
        public byte LoaiNguoiDung { get; set; }
        public string MoTa { get; set; }
        public bool SuDung { get; set; }
        public int MaNoiDangKy { get; set; }
        public bool DaDoiMatKhau { get; set; }
        public bool DaXoa { get; set; }
    
        public virtual ADM_NoiDangKy ADM_NoiDangKy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_ChoLocPhienGuiDuLieu> DAT_ChoLocPhienGuiDuLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_ChuyenDoiDiaGioi> DAT_ChuyenDoiDiaGioi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_NhapLieuGSPH> DAT_NhapLieuGSPH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_NhapLieuGSPH> DAT_NhapLieuGSPH1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_NhapLieuGSPH> DAT_NhapLieuGSPH2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_NhapLieuGSTD> DAT_NhapLieuGSTD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_NhapLieuGSTD> DAT_NhapLieuGSTD1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_NhapLieuGSTD> DAT_NhapLieuGSTD2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_NhapLieuXetNghiem> DAT_NhapLieuXetNghiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_NhapLieuXetNghiem> DAT_NhapLieuXetNghiem1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_NhapLieuXetNghiem> DAT_NhapLieuXetNghiem2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_PhienGuiDuLieu> DAT_PhienGuiDuLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_PhienNhanDuLieu> DAT_PhienNhanDuLieu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIC_NhapLieuTuDien> DIC_NhapLieuTuDien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIC_NhapLieuTuDien> DIC_NhapLieuTuDien1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIC_NhapLieuTuDien> DIC_NhapLieuTuDien2 { get; set; }
    }
}
