//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_CapMaDangKy
    {
        public int MaNoiDangKy { get; set; }
        public byte LanCap { get; set; }
        public string MaSoMauGSPHMax { get; set; }
        public string MaSoMauGSTDMax { get; set; }
        public string MaSoMauXetNghiemMax { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual ADM_NoiDangKy ADM_NoiDangKy { get; set; }
    }
}
