//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADM_UPDATE_PROC
    {
        public string PROC_NAME { get; set; }
        public Nullable<int> PROC_VERSION { get; set; }
        public Nullable<bool> IsExist { get; set; }
    }
}
