//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_ChoLocMauGSPH_HIV
    {
        public string MaSo { get; set; }
        public Nullable<System.DateTime> NgayXetNghiem { get; set; }
        public Nullable<short> IDNoiLayMau { get; set; }
        public Nullable<short> IDNoiXN { get; set; }
        public int MaNoiDangKy { get; set; }
    
        public virtual ADM_NoiDangKy ADM_NoiDangKy { get; set; }
        public virtual DAT_ChoLocMauGSPH DAT_ChoLocMauGSPH { get; set; }
        public virtual DIC_NoiLayMau DIC_NoiLayMau { get; set; }
        public virtual DIC_NoiXetNghiem DIC_NoiXetNghiem { get; set; }
    }
}
