//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_GuiDuLieuGSTD
    {
        public string MaSo { get; set; }
        public int IDPhienGui { get; set; }
        public bool GuiLai { get; set; }
    
        public virtual DAT_MauGSTD DAT_MauGSTD { get; set; }
        public virtual DAT_PhienGuiDuLieu DAT_PhienGuiDuLieu { get; set; }
    }
}
