//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_XetNghiemKQHIVCT
    {
        public Nullable<long> IDDoiTuong { get; set; }
        public string TenDoiTuong { get; set; }
        public Nullable<int> TreEm { get; set; }
        public Nullable<int> ThanhNien { get; set; }
        public Nullable<int> TrungNien { get; set; }
        public Nullable<int> CaoTuoi { get; set; }
        public Nullable<int> Nam { get; set; }
        public Nullable<int> Nu { get; set; }
        public Nullable<int> KhongRo { get; set; }
        public Nullable<int> TTreEm { get; set; }
        public Nullable<int> TThanhNien { get; set; }
        public Nullable<int> TTrungNien { get; set; }
        public Nullable<int> TCaoTuoi { get; set; }
        public Nullable<int> TNam { get; set; }
        public Nullable<int> TNu { get; set; }
        public Nullable<int> TKhongRo { get; set; }
        public long ID { get; set; }
        public string IDXetNghiem { get; set; }
    }
}
