//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_ChoLocPhienNhanDuLieu
    {
        public int IDPhienNhan { get; set; }
        public string MoTa { get; set; }
        public System.DateTime NgayNhan { get; set; }
        public short IDNguoiNhan { get; set; }
        public Nullable<int> IDPhienNhanSangLoc { get; set; }
    }
}
