//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_MauGSPH_AIDS_DieuTri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAT_MauGSPH_AIDS_DieuTri()
        {
            this.DAT_MauGSPH_AIDS_DieuTri_PhacDo = new HashSet<DAT_MauGSPH_AIDS_DieuTri_PhacDo>();
        }
    
        public string MaSo { get; set; }
        public short IDCoSo { get; set; }
        public System.DateTime NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        public virtual DAT_MauGSPH_AIDS DAT_MauGSPH_AIDS { get; set; }
        public virtual DIC_CoSoDieuTri DIC_CoSoDieuTri { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_MauGSPH_AIDS_DieuTri_PhacDo> DAT_MauGSPH_AIDS_DieuTri_PhacDo { get; set; }
    }
}
