//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_ChoLocMauGSPH_TuVong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAT_ChoLocMauGSPH_TuVong()
        {
            this.DIC_NguyenNhanTuVong = new HashSet<DIC_NguyenNhanTuVong>();
        }
    
        public string MaSo { get; set; }
        public Nullable<System.DateTime> NgayTuVong { get; set; }
        public int MaNoiDangKy { get; set; }
    
        public virtual ADM_NoiDangKy ADM_NoiDangKy { get; set; }
        public virtual DAT_ChoLocMauGSPH DAT_ChoLocMauGSPH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIC_NguyenNhanTuVong> DIC_NguyenNhanTuVong { get; set; }
    }
}
