//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;

    public partial class DAT_MauGSPH_HIV
    {
        public string MaSo { get; set; }
        public Nullable<System.DateTime> NgayXetNghiem { get; set; }
        public Nullable<short> IDNoiLayMau { get; set; }
        public Nullable<short> IDNoiXN { get; set; }
        public int MaNoiDangKy { get; set; }
        public Nullable<byte> IDTrangThaiDieuTriHIV { get; set; }
        public string NguonSoLieu { get; set; }
    }
}
