//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_ChoLocMauGSPH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAT_ChoLocMauGSPH()
        {
            this.DAT_ChoLocMauGSPH_TheoDoi = new HashSet<DAT_ChoLocMauGSPH_TheoDoi>();
        }
    
        public string MaSo { get; set; }
        public string HoTen { get; set; }
        public Nullable<byte> IDDanToc { get; set; }
        public string SoCMND { get; set; }
        public Nullable<byte> IDGioiTinh { get; set; }
        public Nullable<short> NamSinh { get; set; }
        public Nullable<int> IDXaHK { get; set; }
        public Nullable<int> IDHuyenHK { get; set; }
        public Nullable<short> IDTinhHK { get; set; }
        public string DuongPhoHK { get; set; }
        public string ToHK { get; set; }
        public string SoNhaHK { get; set; }
        public Nullable<int> IDXaTT { get; set; }
        public Nullable<int> IDHuyenTT { get; set; }
        public Nullable<short> IDTinhTT { get; set; }
        public string DuongPhoTT { get; set; }
        public string ToTT { get; set; }
        public string SoNhaTT { get; set; }
        public Nullable<byte> IDNgheNghiep { get; set; }
        public Nullable<byte> IDDoiTuong { get; set; }
        public Nullable<byte> IDDuongLay { get; set; }
        public Nullable<byte> IDNguyCo { get; set; }
        public Nullable<byte> IDTinhTrang { get; set; }
        public string GhiChu { get; set; }
        public int MaNoiDangKy { get; set; }
        public Nullable<bool> DaGui { get; set; }
    
        public virtual ADM_NoiDangKy ADM_NoiDangKy { get; set; }
        public virtual DAT_ChoLocGuiDuLieuGSPH DAT_ChoLocGuiDuLieuGSPH { get; set; }
        public virtual DAT_ChoLocMauGSPH_AIDS DAT_ChoLocMauGSPH_AIDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_ChoLocMauGSPH_TheoDoi> DAT_ChoLocMauGSPH_TheoDoi { get; set; }
        public virtual DIC_DanToc DIC_DanToc { get; set; }
        public virtual DIC_DoiTuong DIC_DoiTuong { get; set; }
        public virtual DIC_DuongLay DIC_DuongLay { get; set; }
        public virtual DIC_GioiTinh DIC_GioiTinh { get; set; }
        public virtual DIC_NgheNghiep DIC_NgheNghiep { get; set; }
        public virtual DIC_NguyCoLayNhiem DIC_NguyCoLayNhiem { get; set; }
        public virtual DIC_QuanHuyen DIC_QuanHuyen { get; set; }
        public virtual DIC_QuanHuyen DIC_QuanHuyen1 { get; set; }
        public virtual DIC_TinhThanh DIC_TinhThanh { get; set; }
        public virtual DIC_TinhThanh DIC_TinhThanh1 { get; set; }
        public virtual DIC_TinhTrangHienTai DIC_TinhTrangHienTai { get; set; }
        public virtual DIC_XaPhuong DIC_XaPhuong { get; set; }
        public virtual DIC_XaPhuong DIC_XaPhuong1 { get; set; }
        public virtual DAT_ChoLocMauGSPH_HIV DAT_ChoLocMauGSPH_HIV { get; set; }
        public virtual DAT_ChoLocMauGSPH_TuVong DAT_ChoLocMauGSPH_TuVong { get; set; }
    }
}
