//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_MauGSPH_HIV_DieuTri
    {
        public string MaSo { get; set; }
        public short IDCoSo { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<byte> CoBaoHiem { get; set; }
        public Nullable<System.DateTime> NgayBatDauBH { get; set; }
        public Nullable<System.DateTime> NgayKetThucBH { get; set; }
        public string SoTheBH { get; set; }
        public Nullable<System.DateTime> NgayBatDauDT { get; set; }
        public string PhacDoBatDau { get; set; }
        public string PhacDoDieuTri { get; set; }
        public string LoaiDangKy { get; set; }
        public string LyDoKetThuc { get; set; }
    }
}
