//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_NhapLieuXetNghiem
    {
        public string MaSo { get; set; }
        public short IDNguoiNhap { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public Nullable<short> IDNguoiSua { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<short> IDNguoiXoa { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
    
        public virtual ADM_NguoiDung ADM_NguoiDung { get; set; }
        public virtual ADM_NguoiDung ADM_NguoiDung1 { get; set; }
        public virtual ADM_NguoiDung ADM_NguoiDung2 { get; set; }
        public virtual DAT_MauXetNghiem DAT_MauXetNghiem { get; set; }
    }
}
