//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_XetNghiemKQHIV
    {
        public long ID { get; set; }
        public string IDXetNghiem { get; set; }
        public Nullable<long> IDTinh { get; set; }
        public Nullable<long> IDHuyen { get; set; }
        public Nullable<System.DateTime> NgayThang { get; set; }
        public Nullable<long> DaGui { get; set; }
        public Nullable<int> MaNoiDangKy { get; set; }
    }
}
