//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_MauGSTD_BenhLayTruyen
    {
        public string MaSo { get; set; }
        public byte IDBenh { get; set; }
        public byte IDKetQua { get; set; }
    
        public virtual DAT_MauGSTD DAT_MauGSTD { get; set; }
        public virtual DIC_BenhLayTruyen DIC_BenhLayTruyen { get; set; }
        public virtual DIC_KetQua DIC_KetQua { get; set; }
    }
}
