//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_MauGSPH_TheoDoi
    {
        public long IDTheoDoi { get; set; }
        public string MaSo { get; set; }
        public System.DateTime NgayTheoDoi { get; set; }
        public Nullable<byte> IDChucNangVanDong { get; set; }
        public Nullable<decimal> ChieuCao { get; set; }
        public Nullable<decimal> CanNang { get; set; }
        public Nullable<byte> IDTrieuChung { get; set; }
        public Nullable<short> TriSoCD4 { get; set; }
        public Nullable<byte> PhanBiet { get; set; }
    
        public virtual DAT_MauGSPH DAT_MauGSPH { get; set; }
        public virtual DIC_ChucNangVanDong DIC_ChucNangVanDong { get; set; }
        public virtual DIC_TrieuChung DIC_TrieuChung { get; set; }
    }
}
