//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_MauXetNghiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAT_MauXetNghiem()
        {
            this.DAT_ChuyenDoiXetNghiem = new HashSet<DAT_ChuyenDoiXetNghiem>();
            this.DAT_GuiDuLieuXetNghiem = new HashSet<DAT_GuiDuLieuXetNghiem>();
            this.DAT_PhienNhanDuLieu = new HashSet<DAT_PhienNhanDuLieu>();
        }
    
        public string MaSo { get; set; }
        public string HoTen { get; set; }
        public byte IDGioiTinh { get; set; }
        public short NamSinh { get; set; }
        public Nullable<byte> IDNghe { get; set; }
        public byte IDDoiTuong { get; set; }
        public byte IDDuongLay { get; set; }
        public Nullable<short> IDTinhTT { get; set; }
        public Nullable<int> IDHuyenTT { get; set; }
        public Nullable<int> IDXaTT { get; set; }
        public string ToTT { get; set; }
        public string DuongPhoTT { get; set; }
        public string SoNhaTT { get; set; }
        public short IDNoiLayMau { get; set; }
        public System.DateTime NgayLayMau { get; set; }
        public System.DateTime NgayCoKetQua { get; set; }
        public Nullable<byte> IDLoaiSinhPhamPC1 { get; set; }
        public Nullable<byte> IDLoaiSinhPhamPC2 { get; set; }
        public Nullable<byte> IDLoaiSinhPhamPC3 { get; set; }
        public Nullable<byte> IDKQPhuongCach1 { get; set; }
        public Nullable<byte> IDKQPhuongCach2 { get; set; }
        public Nullable<byte> IDKQPhuongCach3 { get; set; }
        public byte IDKQCuoiCung { get; set; }
        public Nullable<short> IDNoiXN { get; set; }
        public string GhiChu { get; set; }
        public int MaNoiDangKy { get; set; }
        public Nullable<bool> DaGui { get; set; }
    
        public virtual ADM_NoiDangKy ADM_NoiDangKy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_ChuyenDoiXetNghiem> DAT_ChuyenDoiXetNghiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_GuiDuLieuXetNghiem> DAT_GuiDuLieuXetNghiem { get; set; }
        public virtual DIC_DoiTuong DIC_DoiTuong { get; set; }
        public virtual DIC_DuongLay DIC_DuongLay { get; set; }
        public virtual DIC_GioiTinh DIC_GioiTinh { get; set; }
        public virtual DIC_KetQua DIC_KetQua { get; set; }
        public virtual DIC_KetQua DIC_KetQua1 { get; set; }
        public virtual DIC_KetQua DIC_KetQua2 { get; set; }
        public virtual DIC_KetQua DIC_KetQua3 { get; set; }
        public virtual DIC_NgheNghiep DIC_NgheNghiep { get; set; }
        public virtual DIC_NoiLayMau DIC_NoiLayMau { get; set; }
        public virtual DIC_NoiXetNghiem DIC_NoiXetNghiem { get; set; }
        public virtual DIC_QuanHuyen DIC_QuanHuyen { get; set; }
        public virtual DIC_SinhPhamXetNghiem DIC_SinhPhamXetNghiem { get; set; }
        public virtual DIC_SinhPhamXetNghiem DIC_SinhPhamXetNghiem1 { get; set; }
        public virtual DIC_SinhPhamXetNghiem DIC_SinhPhamXetNghiem2 { get; set; }
        public virtual DIC_SinhPhamXetNghiem DIC_SinhPhamXetNghiem3 { get; set; }
        public virtual DIC_TinhThanh DIC_TinhThanh { get; set; }
        public virtual DIC_XaPhuong DIC_XaPhuong { get; set; }
        public virtual DAT_NhapLieuXetNghiem DAT_NhapLieuXetNghiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_PhienNhanDuLieu> DAT_PhienNhanDuLieu { get; set; }
    }
}
