//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DAT_MauGSTD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DAT_MauGSTD()
        {
            this.DAT_ChuyenDoiGSTD = new HashSet<DAT_ChuyenDoiGSTD>();
            this.DAT_GuiDuLieuGSTD = new HashSet<DAT_GuiDuLieuGSTD>();
            this.DAT_MauGSTD_BenhLayTruyen = new HashSet<DAT_MauGSTD_BenhLayTruyen>();
            this.DAT_PhienNhanDuLieu = new HashSet<DAT_PhienNhanDuLieu>();
        }
    
        public string MaSo { get; set; }
        public short Nam { get; set; }
        public string MaNhanBiet { get; set; }
        public byte IDDoiTuong { get; set; }
        public byte IDDiaDiem { get; set; }
        public Nullable<System.DateTime> NgayVao { get; set; }
        public Nullable<byte> IDViTri { get; set; }
        public short NamSinh { get; set; }
        public byte IDGioiTinh { get; set; }
        public Nullable<byte> IDNghe { get; set; }
        public Nullable<short> IDTinh { get; set; }
        public Nullable<int> IDHuyen { get; set; }
        public Nullable<int> IDXa { get; set; }
        public bool TiemChich { get; set; }
        public Nullable<System.DateTime> NgayTiemChich { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> MaNoiDangKy { get; set; }
        public Nullable<bool> DaGui { get; set; }
    
        public virtual ADM_NoiDangKy ADM_NoiDangKy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_ChuyenDoiGSTD> DAT_ChuyenDoiGSTD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_GuiDuLieuGSTD> DAT_GuiDuLieuGSTD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_MauGSTD_BenhLayTruyen> DAT_MauGSTD_BenhLayTruyen { get; set; }
        public virtual DIC_DiaDiemGiamSat DIC_DiaDiemGiamSat { get; set; }
        public virtual DIC_DoiTuong DIC_DoiTuong { get; set; }
        public virtual DIC_GioiTinh DIC_GioiTinh { get; set; }
        public virtual DIC_NgheNghiep DIC_NgheNghiep { get; set; }
        public virtual DIC_QuanHuyen DIC_QuanHuyen { get; set; }
        public virtual DIC_TinhThanh DIC_TinhThanh { get; set; }
        public virtual DIC_ViTriLayMau DIC_ViTriLayMau { get; set; }
        public virtual DIC_XaPhuong DIC_XaPhuong { get; set; }
        public virtual DAT_NhapLieuGSTD DAT_NhapLieuGSTD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_PhienNhanDuLieu> DAT_PhienNhanDuLieu { get; set; }
    }
}
