//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_TrangThaiDieuTri
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_TrangThaiDieuTri()
        {
            this.DAT_ChoLocMauGSPH_AIDS = new HashSet<DAT_ChoLocMauGSPH_AIDS>();
            this.DAT_MauGSPH_AIDS = new HashSet<DAT_MauGSPH_AIDS>();
        }
    
        public byte IDTrangThaiDieuTri { get; set; }
        public string MoTa { get; set; }
        public bool SuDung { get; set; }
        public bool DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_ChoLocMauGSPH_AIDS> DAT_ChoLocMauGSPH_AIDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_MauGSPH_AIDS> DAT_MauGSPH_AIDS { get; set; }
    }
}
