//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_BenhLayTruyen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_BenhLayTruyen()
        {
            this.DAT_MauGSTD_BenhLayTruyen = new HashSet<DAT_MauGSTD_BenhLayTruyen>();
        }
    
        public byte IDBenh { get; set; }
        public Nullable<byte> IDBenhCha { get; set; }
        public string TenBenh { get; set; }
        public bool SuDung { get; set; }
        public bool DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_MauGSTD_BenhLayTruyen> DAT_MauGSTD_BenhLayTruyen { get; set; }
    }
}
