//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_cosodieutritmp
    {
        public short IDCoSo { get; set; }
        public string TenCoSo { get; set; }
        public Nullable<short> IDTinh { get; set; }
        public bool SuDung { get; set; }
        public bool DaXoa { get; set; }
    }
}
