//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_TrieuChung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_TrieuChung()
        {
            this.DAT_ChoLocMauGSPH_TheoDoi = new HashSet<DAT_ChoLocMauGSPH_TheoDoi>();
            this.DAT_MauGSPH_TheoDoi = new HashSet<DAT_MauGSPH_TheoDoi>();
        }
    
        public byte IDTrieuChung { get; set; }
        public string TenTrieuChung { get; set; }
        public bool SuDung { get; set; }
        public bool DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_ChoLocMauGSPH_TheoDoi> DAT_ChoLocMauGSPH_TheoDoi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_MauGSPH_TheoDoi> DAT_MauGSPH_TheoDoi { get; set; }
    }
}
