//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_NoiLayMau
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_NoiLayMau()
        {
            this.DAT_ChoLocMauGSPH_HIV = new HashSet<DAT_ChoLocMauGSPH_HIV>();
            this.DAT_MauXetNghiem = new HashSet<DAT_MauXetNghiem>();
            this.DIC_NoiLayMau1 = new HashSet<DIC_NoiLayMau>();
        }
    
        public short IDNoiLayMau { get; set; }
        public Nullable<short> IDNhomCha { get; set; }
        public string TenNoiLayMau { get; set; }
        public Nullable<short> IDTinh { get; set; }
        public bool SuDung { get; set; }
        public bool DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_ChoLocMauGSPH_HIV> DAT_ChoLocMauGSPH_HIV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_MauXetNghiem> DAT_MauXetNghiem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIC_NoiLayMau> DIC_NoiLayMau1 { get; set; }
        public virtual DIC_NoiLayMau DIC_NoiLayMau2 { get; set; }
        public virtual DIC_TinhThanh DIC_TinhThanh { get; set; }
    }
}
