//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_NoiXetNghiem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_NoiXetNghiem()
        {
            this.DAT_ChoLocMauGSPH_AIDS = new HashSet<DAT_ChoLocMauGSPH_AIDS>();
            this.DAT_ChoLocMauGSPH_HIV = new HashSet<DAT_ChoLocMauGSPH_HIV>();
            this.DAT_MauXetNghiem = new HashSet<DAT_MauXetNghiem>();
        }
    
        public short IDNoiXN { get; set; }
        public string TenNoiXN { get; set; }
        public string TenVietTat { get; set; }
        public Nullable<short> IDTinh { get; set; }
        public bool SuDung { get; set; }
        public bool DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_ChoLocMauGSPH_AIDS> DAT_ChoLocMauGSPH_AIDS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_ChoLocMauGSPH_HIV> DAT_ChoLocMauGSPH_HIV { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_MauXetNghiem> DAT_MauXetNghiem { get; set; }
        public virtual DIC_TinhThanh DIC_TinhThanh { get; set; }
    }
}
