//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIC_NguyenNhanTuVong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIC_NguyenNhanTuVong()
        {
            this.DAT_ChoLocMauGSPH_TuVong = new HashSet<DAT_ChoLocMauGSPH_TuVong>();
            this.DAT_MauGSPH_TuVong = new HashSet<DAT_MauGSPH_TuVong>();
        }
    
        public byte IDNguyenNhan { get; set; }
        public string TenNguyenNhan { get; set; }
        public bool SuDung { get; set; }
        public bool DaXoa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_ChoLocMauGSPH_TuVong> DAT_ChoLocMauGSPH_TuVong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DAT_MauGSPH_TuVong> DAT_MauGSPH_TuVong { get; set; }
    }
}
