//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class HIV_AIDS_HK
    {
        public string MaSo { get; set; }
        public string HoTen { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<short> NamSinh { get; set; }
        public Nullable<int> CB { get; set; }
        public string NgheNghiep { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public string DiaChi { get; set; }
        public string DuongPho { get; set; }
        public string To { get; set; }
        public string SoNha { get; set; }
        public string DoiTuong { get; set; }
        public string NguyCoLayNhiem { get; set; }
        public string NgayXNHIV { get; set; }
        public string NgayCDAIDS { get; set; }
        public string IDTrieuChung { get; set; }
        public int MaNoiDangKy { get; set; }
        public Nullable<short> IDTinhHK { get; set; }
        public Nullable<int> IDHuyenHK { get; set; }
        public Nullable<int> IDXaHK { get; set; }
    }
}
