//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DoiTuongTrongDiem
    {
        public byte IDDoiTuong { get; set; }
        public Nullable<byte> IDDoiTuongCha { get; set; }
        public string TenVietTat { get; set; }
        public string TenDayDu { get; set; }
        public bool MauGSPH { get; set; }
        public bool MauGSTD { get; set; }
        public bool MauXetNghiem { get; set; }
        public bool SuDung { get; set; }
        public bool DaXoa { get; set; }
    }
}
