//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DIC_NgheNghiep_GSTD
    {
        public byte IDNghe { get; set; }
        public string TenNghe { get; set; }
        public bool SuDung { get; set; }
        public bool DaXoa { get; set; }
    }
}
