//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_DoiTuongXetNghiem
    {
        public byte IDDoiTuong { get; set; }
        public string TenDayDu { get; set; }
        public byte IDGioiTinh { get; set; }
    }
}
