//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_HIVAIDS_PI_NHATRANG
    {
        public string TenTinhHK { get; set; }
        public string TenTinhTT { get; set; }
        public string TenHuyenHK { get; set; }
        public string TenHuyenTT { get; set; }
        public string TenXaHK { get; set; }
        public string TenXaTT { get; set; }
        public string TenDanToc { get; set; }
        public string TenGioiTinh { get; set; }
        public string NgheNghiep { get; set; }
        public string DoiTuong { get; set; }
        public string DuongLay { get; set; }
        public string NguyCo { get; set; }
        public string TinhTrangCuTru { get; set; }
        public string MaSo { get; set; }
        public string HoTen { get; set; }
        public Nullable<byte> IDDanToc { get; set; }
        public string SoCMND { get; set; }
        public Nullable<byte> IDGioiTinh { get; set; }
        public Nullable<short> NamSinh { get; set; }
        public Nullable<int> IDXaHK { get; set; }
        public Nullable<int> IDHuyenHK { get; set; }
        public Nullable<short> IDTinhHK { get; set; }
        public string DuongPhoHK { get; set; }
        public string ToHK { get; set; }
        public string SoNhaHK { get; set; }
        public Nullable<int> IDXaTT { get; set; }
        public Nullable<int> IDHuyenTT { get; set; }
        public Nullable<short> IDTinhTT { get; set; }
        public string DuongPhoTT { get; set; }
        public string ToTT { get; set; }
        public string SoNhaTT { get; set; }
        public Nullable<byte> IDNgheNghiep { get; set; }
        public Nullable<byte> IDDoiTuong { get; set; }
        public Nullable<byte> IDDuongLay { get; set; }
        public Nullable<byte> IDNguyCo { get; set; }
        public Nullable<byte> IDTinhTrang { get; set; }
        public int MaNoiDangKy { get; set; }
        public Nullable<bool> DaGui { get; set; }
        public Nullable<System.DateTime> NgayXetNghiemHIV { get; set; }
        public Nullable<short> IDNoiLayMauHIV { get; set; }
        public string NoiLayMauHIV { get; set; }
        public Nullable<short> IDNoiXNHIV { get; set; }
        public string NoiXetNghiemHIV { get; set; }
        public Nullable<System.DateTime> NgayCDAIDS { get; set; }
        public Nullable<short> IDNoiChanDoanAIDS { get; set; }
        public string NoiChanDoanAIDS { get; set; }
        public Nullable<byte> IDTrangThaiDieuTri { get; set; }
        public string TrangThaiDieuTriAIDS { get; set; }
        public Nullable<System.DateTime> NgayBDDieuTri { get; set; }
        public Nullable<System.DateTime> NgayKTDieuTri { get; set; }
        public string CoSoDieuTri { get; set; }
        public Nullable<short> IDCoSoDieuTri { get; set; }
        public Nullable<System.DateTime> NgayTuVong { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public System.DateTime NgayNhapHIV { get; set; }
        public Nullable<System.DateTime> NgayNhapAIDS { get; set; }
        public Nullable<System.DateTime> NgayNhapTuVong { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<byte> IDLoaiBenh { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
    }
}
