//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_KetXuatXN
    {
        public string MaSo { get; set; }
        public string HoTen { get; set; }
        public byte IDGioiTinh { get; set; }
        public short NamSinh { get; set; }
        public Nullable<byte> IDNghe { get; set; }
        public byte IDDoiTuong { get; set; }
        public byte IDDuongLay { get; set; }
        public Nullable<short> IDTinhTT { get; set; }
        public Nullable<int> IDHuyenTT { get; set; }
        public Nullable<int> IDXaTT { get; set; }
        public string ToTT { get; set; }
        public string DuongPhoTT { get; set; }
        public string SoNhaTT { get; set; }
        public short IDNoiLayMau { get; set; }
        public System.DateTime NgayLayMau { get; set; }
        public System.DateTime NgayCoKetQua { get; set; }
        public byte IDKQCuoiCung { get; set; }
        public Nullable<short> IDnoiXN { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
    }
}
