//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_KetXuatGSPH
    {
        public System.DateTime NgayNhap { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<System.DateTime> NgayNhapAIDS { get; set; }
        public Nullable<System.DateTime> NgayNhapTuVong { get; set; }
        public string MaSo { get; set; }
        public string HoTen { get; set; }
        public Nullable<byte> IDGioiTinh { get; set; }
        public Nullable<short> NamSinh { get; set; }
        public Nullable<byte> IDNgheNghiep { get; set; }
        public Nullable<byte> IDDoiTuong { get; set; }
        public Nullable<byte> IDNguyCo { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<System.DateTime> NgayXetNghiem { get; set; }
        public Nullable<short> IDNoiLayMau { get; set; }
        public Nullable<short> IDNoiXNHIV { get; set; }
        public Nullable<System.DateTime> NgayCDAIDS { get; set; }
        public Nullable<short> IDNoiXNAIDS { get; set; }
        public Nullable<System.DateTime> NgayTuVong { get; set; }
        public Nullable<byte> LoaiBenh { get; set; }
        public string NNTV { get; set; }
        public string TrieuChung { get; set; }
        public Nullable<byte> IDTinhTrang { get; set; }
        public Nullable<byte> IDDuongLay { get; set; }
        public Nullable<int> IDXaHK { get; set; }
        public Nullable<short> IDTinhTT { get; set; }
        public Nullable<int> IDHuyenHK { get; set; }
        public Nullable<short> IDTinhHK { get; set; }
        public Nullable<int> IDXaTT { get; set; }
        public Nullable<int> IDHuyenTT { get; set; }
        public string TenTinh { get; set; }
        public string TenHuyen { get; set; }
        public string TenXa { get; set; }
        public Nullable<byte> IDTrangThaiDieuTri { get; set; }
        public Nullable<byte> IDDanToc { get; set; }
    }
}
