//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_KetXuatGSTD
    {
        public string MaSo { get; set; }
        public short Nam { get; set; }
        public string MaNhanBiet { get; set; }
        public byte IDDoiTuong { get; set; }
        public byte IDDiaDiem { get; set; }
        public System.DateTime NgayVao { get; set; }
        public Nullable<byte> IDViTri { get; set; }
        public short NamSinh { get; set; }
        public byte IDGioiTinh { get; set; }
        public byte IDNghe { get; set; }
        public int IDHuyen { get; set; }
        public int IDXa { get; set; }
        public bool TiemChich { get; set; }
        public System.DateTime NgayTiemChich { get; set; }
        public Nullable<int> MaNoiDangKy { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public System.DateTime NgaySua { get; set; }
        public System.DateTime NgayXoa { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public short IDTinh { get; set; }
        public string IDBenhLayTruyen { get; set; }
    }
}
