//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_MauGSPH_ChuaRaSoat
    {
        public string MaSo { get; set; }
        public string HoTen { get; set; }
        public Nullable<byte> IDDanToc { get; set; }
        public string SoCMND { get; set; }
        public Nullable<byte> IDGioiTinh { get; set; }
        public Nullable<short> NamSinh { get; set; }
        public Nullable<int> IDXaHK { get; set; }
        public Nullable<int> IDHuyenHK { get; set; }
        public Nullable<short> IDTinhHK { get; set; }
        public string DuongPhoHK { get; set; }
        public string ToHK { get; set; }
        public string SoNhaHK { get; set; }
        public Nullable<int> IDXaTT { get; set; }
        public Nullable<int> IDHuyenTT { get; set; }
        public Nullable<short> IDTinhTT { get; set; }
        public string DuongPhoTT { get; set; }
        public string ToTT { get; set; }
        public string SoNhaTT { get; set; }
        public Nullable<byte> IDNgheNghiep { get; set; }
        public Nullable<byte> IDDoiTuong { get; set; }
        public Nullable<byte> IDDuongLay { get; set; }
        public Nullable<byte> IDNguyCo { get; set; }
        public Nullable<byte> IDTinhTrang { get; set; }
        public string GhiChu { get; set; }
        public int MaNoiDangKy { get; set; }
        public Nullable<bool> DaGui { get; set; }
        public string NgayXetNghiem { get; set; }
        public Nullable<byte> IDNoiLayMau { get; set; }
        public Nullable<byte> IDNoiXetNghiem { get; set; }
        public string NgayCDAIDS { get; set; }
        public Nullable<byte> IDNoiCD { get; set; }
        public Nullable<byte> IDTrangThaiDieuTri { get; set; }
        public string DanToc { get; set; }
        public string DuongLay { get; set; }
        public string GioiTinh { get; set; }
        public string NoiLayMau { get; set; }
        public string NoiXetNghiem { get; set; }
        public string NguyCo { get; set; }
        public string NgheNghiep { get; set; }
        public string TinhTrangHienTai { get; set; }
        public string TinhHK { get; set; }
        public string HuyenHK { get; set; }
        public string XaHK { get; set; }
        public string TinhTT { get; set; }
        public string HuyenTT { get; set; }
        public string XaTT { get; set; }
        public string DoiTuong { get; set; }
        public string TrangThaiDieuTri { get; set; }
        public string NgayTuVong { get; set; }
        public string NoiChanDoan { get; set; }
        public Nullable<byte> IDLoaiBenh { get; set; }
        public string TenLoaiBenhNhan { get; set; }
        public Nullable<int> DaRaSoat { get; set; }
        public string NgayDieuTri { get; set; }
        public Nullable<byte> IDNoiDieuTri { get; set; }
        public string TenNoiDieuTriHIV { get; set; }
    }
}
