//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_MauXetNghiem
    {
        public string MaSo { get; set; }
        public byte IDGioiTinh { get; set; }
        public Nullable<byte> Tuoi { get; set; }
        public byte IDDoiTuong { get; set; }
        public string TenDoiTuong { get; set; }
        public Nullable<short> IDTinhTT { get; set; }
        public Nullable<int> IDHuyenTT { get; set; }
        public Nullable<int> IDXaTT { get; set; }
        public System.DateTime NgayCoKetQua { get; set; }
        public byte IDKQCuoiCung { get; set; }
        public int MaNoiDangKy { get; set; }
        public Nullable<System.DateTime> NgayNhap { get; set; }
    }
}
