//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PhanTichTheoNhomTuoi
    {
        public Nullable<short> IDTinhTT { get; set; }
        public Nullable<short> IDTinhHK { get; set; }
        public string TinhHK { get; set; }
        public string TinhTT { get; set; }
        public Nullable<System.DateTime> NgayNhapXetNghiem { get; set; }
        public Nullable<System.DateTime> NgayNhapTuVong { get; set; }
        public Nullable<System.DateTime> NgayNhapAIDS { get; set; }
        public Nullable<byte> IDNgheNghiep { get; set; }
        public Nullable<byte> IDDoiTuong { get; set; }
        public Nullable<byte> IDGioiTinh { get; set; }
        public Nullable<byte> Tuoi { get; set; }
        public Nullable<System.DateTime> NgayXetNghiem { get; set; }
        public Nullable<System.DateTime> NgayTuVong { get; set; }
        public Nullable<System.DateTime> NgayCDAIDS { get; set; }
        public int MaNoiDangKy { get; set; }
        public string TenHuyenTT { get; set; }
        public string TenHuyenHK { get; set; }
    }
}
