//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ThongKeHIVTheoDoiTuong
    {
        public string MaSo { get; set; }
        public Nullable<byte> IDDoiTuong { get; set; }
        public string TenDoiTuong { get; set; }
        public Nullable<byte> IDNghe { get; set; }
        public string NgheNghiep { get; set; }
        public Nullable<System.DateTime> NgayNhapLieu { get; set; }
        public Nullable<System.DateTime> NgayXetNghiem { get; set; }
        public Nullable<short> TinhHK { get; set; }
        public Nullable<short> TinhTT { get; set; }
        public Nullable<int> HuyenHK { get; set; }
        public Nullable<int> HuyenTT { get; set; }
        public Nullable<int> XaHK { get; set; }
        public Nullable<int> XaTT { get; set; }
        public string TenTinhHK { get; set; }
        public string TenTinhTT { get; set; }
        public Nullable<short> NamSinh { get; set; }
        public Nullable<byte> IDGioiTinh { get; set; }
        public string TenGioiTinh { get; set; }
        public int MaNoiDangKy { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public Nullable<System.DateTime> NgayNhan { get; set; }
        public Nullable<byte> IDDanToc { get; set; }
        public Nullable<byte> IDNguyCo { get; set; }
        public Nullable<short> IDNoiLayMau { get; set; }
        public Nullable<short> IDNoiXN { get; set; }
        public Nullable<byte> IDTrieuChung { get; set; }
        public Nullable<byte> IDTinhTrang { get; set; }
        public string TenHuyenTT { get; set; }
        public string TenHuyenHK { get; set; }
    }
}
