//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobitsHivInfoAdapter
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwBaoCaoKetQuaGSTDTheoKhoangTuoi
    {
        public Nullable<int> MaNoiDangKy { get; set; }
        public Nullable<System.DateTime> NgayXoa { get; set; }
        public byte IDDoiTuong { get; set; }
        public Nullable<short> IDTinh { get; set; }
        public Nullable<int> IDHuyen { get; set; }
        public Nullable<int> IDXa { get; set; }
        public string TenDoiTuong { get; set; }
        public Nullable<byte> IDViTri { get; set; }
        public string TenViTri { get; set; }
        public Nullable<byte> IDNghe { get; set; }
        public byte IDDiaDiem { get; set; }
        public string TenDiaDiem { get; set; }
        public byte IDGioiTinh { get; set; }
        public Nullable<byte> IDBenh { get; set; }
        public Nullable<byte> IDKetQua { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public short Nam { get; set; }
    }
}
